### PR TITLE
Add independent createRoutes method to support v4 react-router

### PR DESCRIPTION
**Pull request by Joseph7451797**
Borrow `createRoutes` function from v3 react-router code base and make it as a internal function. This fixes the missing `createRoutes` method issue which caused by complete rewrite of v4 react-router.

### CODE REVIEW

**Comment by kuflash** [comment]
@Joseph7451797 very good work! Can you change destination branch to `develop`?

**Comment by Joseph7451797** [comment]
> @Joseph7451797 very good work! Can you change destination branch to `develop`?

@kuflash I already changed destination branch to ```develop```, let me know if I need to do more actions or provide something.

**Comment by kuflash** [comment]
@Joseph7451797 I apologize for the late reply. Can you create example for use react-router-4 with react-router-sitemap.  Maybe only code examples in README.md.

**Comment by Joseph7451797** [comment]
@kuflash Code example of v4 `react-router` router setting is similar to old version one and is added to readme. Let me know if more detail is needed.

**Comment by kuflash** [comment]
@Joseph7451797 cool, that is all. Thank you!

**Pull request merged**
